In [1]:
import pandas as pd

In [22]:
df = pd.read_json("data/results_prwp_batch1.jsonl", lines=True)
# df = pd.read_json("data/results_refugee_batch1.jsonl", lines=True)
df

,snapshot_id,image_path,source_label,llm_output,raw_output,usage,cost,error
0,document_10069312_table_006.png,data/prwp_batch1/document_10069312_table_006.png,PRWP,{'visible_text_label': 'Table 7: Intra Africa ...,"{\n ""visible_text_label"": ""Table 7: Intra Afr...","{'input_tokens': 26214, 'input_tokens_details'...","{'input_tokens': 26214, 'output_tokens': 157, ...",None
1,document_11958451_figure_002.png,data/prwp_batch1/document_11958451_figure_002.png,PRWP,{'visible_text_label': 'Figure 2: Russia: Infl...,"{\n ""visible_text_label"": ""Figure 2: Russia: ...","{'input_tokens': 49095, 'input_tokens_details'...","{'input_tokens': 49095, 'output_tokens': 157, ...",None
2,document_11958451_figure_021.png,data/prwp_batch1/document_11958451_figure_021.png,PRWP,{'visible_text_label': 'Figure 20. Average oil...,"{\n ""visible_text_label"": ""Figure 20. Average...","{'input_tokens': 26427, 'input_tokens_details'...","{'input_tokens': 26427, 'output_tokens': 130, ...",None
3,document_700615_table_004.png,data/prwp_batch1/document_700615_table_004.png,PRWP,{'visible_text_label': 'Table A-2 - Dependent ...,"{\n ""visible_text_label"": ""Table A-2 - Depend...","{'input_tokens': 26186, 'input_tokens_details'...","{'input_tokens': 26186, 'output_tokens': 127, ...",None
4,document_11958451_table_001.png,data/prwp_batch1/document_11958451_table_001.png,PRWP,{'visible_text_label': 'Table 2. Consolidated ...,"```json\n{\n ""visible_text_label"": ""Table 2. ...","{'input_tokens': 49095, 'input_tokens_details'...","{'input_tokens': 49095, 'output_tokens': 145, ...",None
...,...,...,...,...,...,...,...,...
392,document_11867889_figure_012.png,data/prwp_batch1/document_11867889_figure_012.png,PRWP,{'visible_text_label': 'Figure 14. Evolution o...,"{\n ""visible_text_label"": ""Figure 14. Evoluti...","{'input_tokens': 48961, 'input_tokens_details'...","{'input_tokens': 48961, 'output_tokens': 146, ...",None
393,document_6731296_table_002.png,data/prwp_batch1/document_6731296_table_002.png,PRWP,{'visible_text_label': 'Table 3 Compensation f...,"```json\n{\n ""visible_text_label"": ""Table 3\n...","{'input_tokens': 26387, 'input_tokens_details'...","{'input_tokens': 26387, 'output_tokens': 141, ...",None
394,document_10002285_table_000.png,data/prwp_batch1/document_10002285_table_000.png,PRWP,{'visible_text_label': 'Table 1 Summary statis...,"```json\n{\n ""visible_text_label"": ""Table 1 S...","{'input_tokens': 48892, 'input_tokens_details'...","{'input_tokens': 48892, 'output_tokens': 138, ...",None
395,document_700561_figure_004.png,data/prwp_batch1/document_700561_figure_004.png,PRWP,{'visible_text_label': 'FREQUENCY DISTRIBUTION...,"{\n ""visible_text_label"": ""FREQUENCY DISTRIBU...","{'input_tokens': 26383, 'input_tokens_details'...","{'input_tokens': 26383, 'output_tokens': 132, ...",None
396,document_1689472_figure_001.png,data/prwp_batch1/document_1689472_figure_001.png,PRWP,{'visible_text_label': 'Figure 2: Frequency Di...,"{\n ""visible_text_label"": ""Figure 2: Frequenc...","{'input_tokens': 37955, 'input_tokens_details'...","{'input_tokens': 37955, 'output_tokens': 120, ...",None

In [23]:
df = df[df["error"].isna()].copy()
df.shape

(396, 8)

In [24]:
df = df.join(pd.json_normalize(df['llm_output'])).drop(columns=['llm_output', "raw_output", "usage", "error"])
df

,snapshot_id,image_path,source_label,cost,visible_text_label,data_modality,topic_domain,population,geographic_scope,temporal_aspect,measurement_units,short_description
0,document_10069312_table_006.png,data/prwp_batch1/document_10069312_table_006.png,PRWP,"{'input_tokens': 26214, 'output_tokens': 157, ...",Table 7: Intra Africa and Rest of world (only ...,statistical analysis results,trade facilitation,unclear,intra-African and global,"single year (2003), pooled cross-section",coefficients and standard errors,The table presents results from a Tobit model ...
1,document_11958451_figure_002.png,data/prwp_batch1/document_11958451_figure_002.png,PRWP,"{'input_tokens': 49095, 'output_tokens': 157, ...",Figure 2: Russia: Inflation and Nominal Deprec...,historical data,economic indicators,unclear,Russia,multi-year trend,"percentages, RUR/USD",This figure presents two economic metrics: the...
2,document_11958451_figure_021.png,data/prwp_batch1/document_11958451_figure_021.png,PRWP,"{'input_tokens': 26427, 'output_tokens': 130, ...",Figure 20. Average oil price in 2008$,historical data,economic indicators,unclear,unclear,1970-2008,dollars per barrel ($/BBL),The figure displays the average oil price from...
3,document_700615_table_004.png,data/prwp_batch1/document_700615_table_004.png,PRWP,"{'input_tokens': 26186, 'output_tokens': 127, ...",Table A-2 - Dependent Variables: ln M(t),model outputs,import demand,countries,country-level,unclear,natural logarithm values,The table reports model outputs for various co...
4,document_11958451_table_001.png,data/prwp_batch1/document_11958451_table_001.png,PRWP,"{'input_tokens': 49095, 'output_tokens': 145, ...","Table 2. Consolidated budget: revenues, expend...",actual fiscal data,fiscal policy,unclear,Russia,multi-year trend (2007-2009),percentages of GDP,The table reports consolidated and federal bud...
...,...,...,...,...,...,...,...,...,...,...,...,...
392,document_11867889_figure_012.png,data/prwp_batch1/document_11867889_figure_012.png,PRWP,"{'input_tokens': 48961, 'output_tokens': 146, ...",Table 3\nCompensation function estimation\nNon...,statistical estimation results,employment and production,manufacturing firms,Uruguay,unclear,coefficients and standard errors,This table presents the results of a non-linea...
393,document_6731296_table_002.png,data/prwp_batch1/document_6731296_table_002.png,PRWP,"{'input_tokens': 26387, 'output_tokens': 141, ...",Table 1 Summary statistics for 110-country mai...,summary statistics,tax policy and administration,countries,global,various years (1999-2006 for some metrics),"mean, standard deviation, minimum, maximum",The table presents summary statistics for vari...
394,document_10002285_table_000.png,data/prwp_batch1/document_10002285_table_000.png,PRWP,"{'input_tokens': 48892, 'output_tokens': 138, ...",FREQUENCY DISTRIBUTION OF HOUSEHOLDS' MONTHLY ...,survey results,livelihoods,households,"Onitsha, Nigeria",unclear,percent of households,The figure displays the percentage of househol...
395,document_700561_figure_004.png,data/prwp_batch1/document_700561_figure_004.png,PRWP,"{'input_tokens': 26383, 'output_tokens': 132, ...",Figure 2: Frequency Distributions for Subjecti...,frequency distribution,financial decision-making,self-employed individuals,Chile,unclear,fraction,The figure displays frequency distributions fo...
396,document_1689472_figure_001.png,data/prwp_batch1/document_1689472_figure_001.png,PRWP,"{'input_tokens': 37955, 'output_tokens': 120, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df2 = df.set_index("snapshot_id")["short_description"].copy()
df2.to_csv("prwp.csv")

In [ ]:
snapshot_id	short_description
document_10069312_table_006.png	The table presents results from a Tobit model analyzing the impacts of various factors, including tariffs and port efficiency, on trade flows within Africa and with the rest of the world. It reports coefficients and standard errors for different fixed effects models.
document_11958451_figure_002.png	This figure presents two economic metrics: the average year-on-year change in the Consumer Price Index (CPI) inflation and the nominal appreciation of the Russian Ruble (RUR) against the US Dollar (USD) across various years.
document_11958451_figure_021.png	The figure displays the average oil price from 1970 to 2008, showing the real oil price, average oil price, and median oil price over the years.
document_700615_table_004.png	The table reports model outputs for various countries, showing the natural logarithm values of income, import price ratios, and other economic variables related to import demand, along with R┬▓ values and instrument sets.
document_11958451_table_001.png	The table reports consolidated and federal budget revenues, expenditures, surpluses, and non-oil balances as percentages of GDP for the years 2007 to 2009.
document_699791_figure_010.png	The figure shows the trend in average bond maturity in days from June 1988 to June 1990, indicating fluctuations over the specified period.
document_15347644_figure_002.png	The figure presents average hours worked per week by older workers and the elderly in urban and rural China, segmented by gender and age, using data from different survey waves.
document_7095002_table_004.png	The table presents descriptive statistics, including means, standard deviations, minimum, and maximum values for various economic and banking indicators, such as GDP per capita, net interest margins, and inflation rates.
document_693460_table_000.png	The table presents data on the loan portfolio of Estonian banks, including total loan amounts and the percentage distribution of loans across various sectors (government, financial institutions, corporations, and individuals) for the years December 1994 to September 1997.
document_6666871_table_007.png	The table presents results from a Tobit model analyzing the determinants of visible land-related investments among households in Uganda, focusing on various factors affecting tree planting.
document_11958451_figure_020.png	The figure depicts the non-oil primary deficit as a share of GDP for various scenarios before and after a crisis, showing different fiscal strategies from 2008 to 2020.
document_10069312_table_001.png	The table presents trade facilitation indicators for various African countries in 2003, measuring aspects such as port efficiency, customs environment, regulatory environment, and services infrastructure.
document_11958451_figure_016.png	The figure illustrates projected long-term fiscal revenues from oil and gas for Russia, showing a significant decline after 2008, with revenues stabilizing around a lower level in subsequent years.
document_6304708_table_000.png	The table reports the structure of value added, factor shares, and the percentages of imports and exports across various sectors in Russia, detailing their share and intensity.
document_10240515_table_003.png	The table presents the distribution of resources (time and money) devoted by registered foreign agents to various activities related to tourism and non-tourism, detailing the percentage allocated for each activity across both categories.
document_11225119_table_005.png	The table reports various metrics related to trade policy adjustments in Tanzania, including the total number of tariff lines, number of excluded product lines, and percentage changes in imports, tariff revenue, and total revenue under different scenarios.
document_11958451_table_002.png	The table summarizes anti-crisis fiscal measures implemented in Russia during 2008 and 2009, detailing their contribution to GDP for specific categories such as strengthening the financial sector and promoting economic growth.
document_12916918_figure_009.png	The snapshot displays the monthly prices and monthly returns (percent change) of platinum over a long time period, including detected breaks in price volatility.
document_700615_table_000.png	The table presents estimates of price and income elasticity of import demand for various countries across different regions, indicating how responsive import demand is to price changes and income variations.
document_2874487_table_001.png	The table reports the effects of political affiliation and other variables on state fiscal deficits in India, presenting regression coefficients for different variables influencing deficits.
document_11867889_figure_008.png	The figure illustrates the evolution of the share of factor content in Argentina's exports and imports from 1992 to 2006, categorizing values into natural resources, unskilled labor, technology, and human capital.
document_6731296_table_003.png	The table presents summary statistics for various employment factors and capital levels, including mean values and standard deviations for actual, desired, and frictionless levels, along with pairwise correlations between different variables.
document_11958451_figure_009.png	The figure presents the strength of correlation between total revenue and total expenditure anti-cyclicality in Russia, showing trends across several time periods from 1992 to 2007.
document_9087385_table_005.png	The table reports the prices of cocaine and heroin at various stages of the supply chain, including farm-gate, export, import, wholesale, and retail stages, with specific price points for different geographic locations.
document_699976_table_000.png	The table reports average food consumption per capita across various countries for the year 1985, detailing calories, protein, and types of food consumed such as meat, fish, vegetables, and grains.
document_7368143_table_007.png	The table reports regression estimates analyzing the impact of the Health Care Fund for the Poor (HCFP) on various out-of-pocket expenses and health service utilization indicators, distinguishing between full and trimmed samples.
document_439628_figure_007.png	The graph depicts the signals generated by an Arima residuals model indicating macroeconomic vulnerability in Mexico preceding the 1994 crisis, with values fluctuating over time.
document_6731296_figure_005.png	The figure displays adjustment functions for white-collar employment, indicating relationships between different categories of shortages and their means, including standard deviation adjustments.
document_14491760_table_000.png	The table presents estimated coefficients for various determinants of migration flows using different econometric methods, including OLS, Heckman models, Poisson estimates, and instrumental variables. It includes variables such as 'Lagged diaspora,' 'Col links,' 'language,' and 'Log(distance),' along with observations and a Mills ratio.
document_438376_table_000.png	The snapshot reports on the average discharges and concentrations of total suspended solids (TSS) and chemical oxygen demand (COD) in water, as well as total suspended particulates (TSP) in air, alongside the proportion of firms paying pollution levies.
document_11992660_table_001.png	The table reports differences in test scores for math, science, English, and total scores between schools with school-based management (SBM) and those without during specified periods, including statistical significance indicators.
document_1689472_table_004.png	The table displays the results of non-parametric tests assessing the significance of differences in risk preferences among specified groups, reporting p-values for different hypotheses regarding risk preference distributions.
document_12916918_figure_010.png	The snapshot presents historical monthly price data for rubber as well as the monthly returns (percentage changes) with indications of detected breaks in the data using the KL (2000) test.
document_11992660_table_003.png	This table reports the results of a statistical analysis estimating propensity scores related to school-based management (SBM) using variables such as student-teacher ratio, school size, and types of schools. It presents coefficients, standard errors, and z-scores for each variable.
document_1689472_figure_004.png	The figure displays individual subjective discount rates for employees and self-employed individuals, visualized through bar graphs indicating the distribution of each group's rates.
document_8886604_table_003.png	The table reports various indicators related to land loss, compensation received, and perceived impacts of land takings, categorized by regions within China.
document_8092215_table_003.png	The table presents the impact of Indian trade flows on non-fuel exports from Latin American and Caribbean countries to third countries, using various econometric models and reporting estimated coefficients along with associated p-values for each regional grouping.
document_8921763_figure_000.png	The figure displays the real GDP trends in Hong Kong, Singapore, and Taiwan (China) from early 2002 through late 2003, reflecting the economic impact of the SARS outbreak.
document_7368143_table_000.png	The table reports descriptive statistics on various health-related expenses and utilization rates for full sample and HCFP eligible households, including total out-of-pocket payments, outpatient and inpatient expenses, and the frequency of healthcare visits.
document_700561_figure_006.png	The figure shows the percentage of household income spent on water during the dry and rainy seasons categorized by different income classes.
document_693460_figure_000.png	The figure presents a trend of bank credits and deposits in Estonia from June 1994 to March 1998, measured in millions of Estonian Kroon (EEK). It shows the growth patterns of both categories over this period.
document_6731296_figure_006.png	The figure presents adjustment functions for blue collar employment, showing different measures of shortages with variations around the mean and standard deviation.
document_6213782_table_000.png	The table reports regression coefficients for fixed capital and labor in relation to total factor productivity (TFP) based on country-survey averages and firm-level data, alongside selected estimates of relative TFP with a benchmark for Serbia in 2002.
document_2160788_table_000.png	The table lists model parameters relevant to the epidemiological study of HIV/AIDS, including rates of transmission, population statistics, and HIV prevalence among various demographic groups.
document_438818_table_004.png	The table presents regression analysis results examining the relationship between various explanatory variables (e.g., leverage, ownership concentration, and types of investors) and firm performance indicators (Tobin's Q and profit) across multiple model specifications.
document_11867889_table_004.png	The table lists Argentina's top export destinations in 2007 and 1997, showing gross export values and their respective shares in total world exports.
document_9089743_figure_000.png	The figure displays a histogram showing the distribution of propensity scores for public sector tea growers, indicating the frequency of scores within specified ranges.
document_439628_table_000.png	The table lists periods of excessive market volatility across several Latin American countries from January 1980 to April 1998, indicating specific time frames for each country.
document_11225119_figure_000.png	The snapshot reports the percentage change in lost tariff revenue for the top ten products in Ethiopia, presented along with their corresponding HS codes.
document_10455617_figure_006.png	The figure compares the services trade restrictiveness index across five sectors (Financial, Telecom, Retailing, Maritime, Professional) reflecting Uruguay Round commitments, Doha offers, and actual policies.
document_700561_figure_002.png	The figure presents daily money and water transactions among various vendors, including tanker trucks, small retail vendors, and households during the rainy season in Onitsha, Nigeria.
document_437731_table_002.png	The table presents probit estimates analyzing the relationship between various explanatory variables, including corruption index, public sector involvement, and financial liberalization, and the occurrence of bank crises.
document_10240515_table_002.png	The table presents estimated elasticities from an IV-GMM model examining the relationship between tourism arrivals, lobbying, real exchange rates, and GDP per capita, noting significance levels and standard errors.
document_12916918_figure_004.png	The data reports breaks in commodity price volatility identified by KL and IT tests, showing the number of 'breaks up' and 'breaks down' over time using a 5-year moving average.
document_9089743_figure_001.png	The figure presents a histogram showing the distribution of propensity scores for private sector tea growers, indicating varying levels of propensity among the growers in the data set.
document_6666871_table_004.png	The table reports on various determinants affecting land productivity, highlighting factors such as tenure security, household characteristics, and land quality, with corresponding statistical significance indicators.
document_10240515_table_001.png	The table reports results of robustness checks for the relationship between tourism arrivals and various factors including lobbying, media lobbying, real exchange rate, and real GDP per capita, using two IV-GMM models.
document_15347644_table_002.png	The table presents the results of linear probability models examining the impact of spouse health and work status on the labor supply decisions of adults over 45 in China, Indonesia, and Korea, measuring factors like pension eligibility and housing wealth.
document_6304708_figure_000.png	This figure displays the distributions of estimated welfare gains as a percentage of consumption for all Russian households, the poorest decile, and the richest decile resulting from global free trade.
document_6731296_figure_007.png	The figure illustrates the adjustment functions related to capital for manufacturing firms in Uruguay, depicting various levels of shortages against a range of factors.
document_11958451_figure_022.png	The figure presents projections of Russia's net debt-to-GDP ratio under different scenarios from 2008 to 2040, comparing baseline situations and fiscal adjustments.
document_6213782_figure_004.png	The figure presents the perceived investment climate constraints faced by firms in Serbia compared to those in other transition countries, measured using various factors such as access to land, electricity, and corruption.
document_8066254_figure_002.png	The figure depicts the annual average discount rate of Israel's DCI bonds compared to the 10-year US Treasury rates from 1953 to 2003.
document_11958451_figure_015.png	The figure illustrates changes in fiscal behavior, specifically savings, expenditures, and non-oil revenues in response to oil shocks from 2003 to 2009, with various colored bars representing different fiscal reactions.
document_11696987_table_004.png	The table presents baseline characteristics of children aged 0-5 years from treatment and comparison groups, including demographic details and preventive medical care indicators.
document_11308693_table_002.png	The table presents survey means categorized by educational attainment, showing metrics such as total remittances, log income, household size, and other demographic factors for migrants across various countries.
document_7368143_table_006.png	The table presents the coefficients and t-statistics from probit estimations of out-of-pocket payments and health service utilization indicators, highlighting sensitivity to different sampling methods.
document_2874487_table_003.png	The table presents regression coefficients and associated t-statistics analyzing the relationship between political affiliation, fiscal transfers, and state fiscal deficits in India. It includes variables related to planning and finance commission grants, state income, and population.
document_439628_figure_006.png	The figure displays an Arima residuals model predicting macroeconomic vulnerability signals in Colombia, highlighting variations in the index values over time leading to the Colombian crisis.
document_11696987_table_000.png	The table lists output indicators related to healthcare visits and content of care, along with the corresponding payments in US dollars for performance-based financing.
document_700561_figure_000.png	The snapshot is a map related to the Anambra Water Supply and Sanitation Project, showing distribution mains, treatment plants, and other relevant infrastructure for water supply in Onitsha, Nigeria.
document_11958451_figure_017.png	The figure presents projected volumes of oil and gas extraction in Russia from 2008 to 2040, with oil extraction volume displayed on the left axis and gas extraction volume on the right axis.
document_6731296_table_001.png	The table presents estimated coefficients and standard errors related to productivity factors such as white collar labor, blue collar hours, materials, machinery capital, and electricity, along with additional statistical metrics.
document_11670035_table_002.png	This table provides summary statistics from a Monte Carlo analysis focused on earthquake propensity across different country classifications, including developing and developed countries, as well as regimes like autocracies and democracies.
document_11696987_table_005.png	The table reports the estimated impact of a pay-for-performance scheme on various maternal and child health care services, detailing utilization rates and quality indicators.
document_6666871_table_003.png	The table presents coefficients and marginal effects from a two-step estimation process analyzing determinants of land-related investments in terms of trees planted, soil conservation, and other factors affecting land use in Uganda.
document_2160788_table_001.png	The table presents projections of adult HIV prevalence in Southern India for the year 2033 under various intervention scenarios, including conventional methods and different vaccine efficacy and response scenarios, with consideration for disinhibition.
document_11696987_table_001.png	The table outlines various health care services along with their quality index weights and the distribution of those weights between structural and process components used to evaluate performance in the Paying for Performance (P4P) scheme.
document_439628_table_004.png	The table presents statistical data for various models applied to several Latin American countries, including unconditional probability, Type I and II errors, noise/signal ratio, and P(C/S) values.
document_12916918_figure_011.png	The snapshot reports on the monthly price of silver over time, alongside the monthly returns expressed as percentage change and breaks detected using the KL (2000) test.
document_10002285_table_003.png	This table reports the results of 2SLS regression analysis examining the impact of sovereign rents, aid, fuel, and metals exports on the efficiency of revenue mobilization, with various specifications outlined in multiple columns.
document_12736370_table_008.png	The table presents the interaction effects of various covariates (such as survey assignment, land size, household size, assets, and child age) on the logarithm of children's hours of work, separately for boys and girls.
document_11867889_table_008.png	This table compares the average annual growth rates of exports from Argentina, Brazil, and Chile, as well as the global average, over specified time periods from 1992 to 2007.
document_699791_figure_000.png	The figure depicts the trade-weighted real exchange rate in Mexico over several years, indicating fluctuations in the rate based on producer price indices.
document_8092215_figure_000.png	The figure presents the share of imports from China and India in Latin America and Caribbean countries, comparing data from the years 1990 and 2004.
document_11958451_figure_003.png	The figure displays the contributions to economic growth in Russia from various sectors, including net exports, gross capital formation, government consumption, and private consumption, over the period from 1996 to 2007.
document_3209477_figure_000.png	The figure reports weekly counts of traffic-related incidents in Bogot├í's central bus network, comparing data before and after the introduction of the Transmilenio system.
document_12736370_table_006.png	The table presents regression analysis results examining the main activities of children classified by survey assignment, showing marginal effects for different types of work (agriculture, domestic) based on survey design (short vs. proxy).
document_12736370_table_004.png	The table presents a regression analysis of labor force participation and conditional hours worked in main jobs for boys and girls, based on two different survey questionnaire designs (short versus proxy).
document_6731296_figure_003.png	The figure displays the output gap of firms in the manufacturing sector in Uruguay, comparing mean and median values over the years 1982 to 1995, reflecting the differences in productivity levels relative to potential output.
document_700561_figure_003.png	The figure presents the frequency distribution of households' willingness-to-pay bids for water, expressed in Naira per 45-gallon drum, showing varying percentages across different bidding ranges.
document_438818_table_001.png	The table presents regression results analyzing the impact of various explanatory variables on Tobin's Q and profit for firms, including factors like ownership concentration and investment funds.
document_439628_table_007.png	The table presents results from various models measuring macroeconomic vulnerability indicators for Latin American countries over a 24-month period from 1986 to 1999, detailing Type I and Type II errors, noise-to-signal ratios, and predictive capabilities across different country models.
document_437731_table_000.png	The table presents counts of banking crises occurring before and after financial liberalization, alongside the counts of liberalizations and their subsequent crisis outcomes.
document_11867889_figure_009.png	The figure presents the Product Concentration Index for Argentina compared to several competitors from 1990 to 2007, showing trends in trade product concentration among these countries over time.
document_1689472_figure_000.png	The snapshot presents a decision card for an experiment on risk aversion, showing two scenarios for investment and insurance decisions with varying profits and costs.
document_6304708_table_003.png	The table presents the distribution of factor income shares (unskilled labor, skilled labor, and capital) along with their standard deviations for households categorized into deciles based on consumption.
document_10455617_figure_000.png	The figure illustrates the relationship between the restrictiveness of services trade policies and GDP per capita across 56 countries, with an overall negative trend indicated by a red line.
document_439628_figure_002.png	The graph displays the signals of macroeconomic vulnerability in Brazil over time, using an Arima residuals model to indicate when a signal is positive, suggesting a period of heightened vulnerability.
document_2874487_table_006.png	The table presents regression coefficients and associated z-statistics for factors influencing revenues and spending of state governments, including variables such as real state income per capita, political affiliation, and various types of grants.
document_8066254_table_001.png	The table summarizes various diaspora bond issuance terms, including time frames and interest rates associated with different periods in Israel's history.
document_8066254_table_000.png	The table lists various bond offerings in Israel, including bond types, issuance dates, maturity periods, minimum investment amounts, and rate bases.
document_15347644_figure_006.png	The figure presents the employed share and labor force participation rate of different demographic groups in China, including urban males, urban females, migrant males, and migrant females, across three years.
document_11958451_figure_007.png	This figure displays the primary general government fiscal balance as a percentage of GDP alongside the price of Russian oil in US dollars per barrel over a timeframe from 1997 to 2007.
document_6213782_table_002.png	The table presents regression coefficients for firm-level data comparing Serbia to other countries, focusing on factors influencing total factor productivity (TFP), including variables such as fixed capital, labor, and ownership types.
document_6731296_table_000.png	The table presents the results of a three-stage least squares regression analyzing demand and supply equations related to gross output in the manufacturing sector, including coefficients and standard errors for various economic parameters.
document_11225119_table_006.png	The table reports on the implications of trade policy changes under the Kenyan EPA, detailing the total number of tariff lines, number of excluded product lines, and the percentage changes in imports, tariff revenue, and total revenue for different exclusion scenarios.
document_10455617_figure_002.png	The figure presents the restrictiveness of services trade policies across different regions, measured by the Services Trade Restrictiveness Index (STRI). South Asia and the Middle East have the highest levels of restrictiveness, while OECD countries show the least.
document_15347644_figure_005.png	The figure presents employment rates by age cohort for urban and rural males and females in China across the years 1990, 2000, and 2005, displaying differences in employment trends among the groups.
document_699791_table_000.png	The table presents the results of an ordinary least squares (OLS) regression analysis, including coefficients, standard errors, and t-statistics for various estimated parameters over the specified sample period.
document_11308693_table_003.png	The table presents coefficients from regression analyses examining the relationship between education (measured by university degree and years of schooling) and remittance behavior among migrants in various countries, detailing both total remittances and margins of remitting behavior.
document_11225119_table_008.png	The table presents the output changes and employment changes for 15 sectors in Mauritius impacted by trade policy changes, measured in million Mauritian Rupees along with percentage changes and changes in employment.
document_6731296_table_005.png	The table presents descriptive statistics on tariff rates, tariff changes, and export-to-sales ratios for manufacturing firms in Uruguay from 1982 to 1995, including mean values, standard deviations, and percentiles.
document_9089743_table_002.png	The table presents a comparison of various outcomes (such as yield per hectare, time to carry leaves, fertilizer use, and costs) between private and public tea sectors in Rwanda, along with their differences in means.
document_15347644_figure_000.png	The figure presents employment rates by age cohort for older workers and elderly individuals in urban and rural areas of China, comparing data from the China Health and Nutrition Survey (CHNS) across different years. It includes gender-specific trends and illustrates the decline in employment rates as age increases.
document_11867889_figure_010.png	The figure illustrates the percentage of import content within exports across various manufacturing sectors in Argentina for the year 1997, highlighting sectors such as motor vehicles, radio and TV receivers, and fertilizers and pesticides.
document_437731_table_001.png	The table reports probit estimates analyzing various explanatory variables affecting the likelihood of a banking crisis in relation to financial liberalization. It includes marginal effects and significance levels of factors such as GDP growth and inflation rate.
document_700561_figure_001.png	This figure illustrates the flow of water and money transactions among various water sources, vendors, and households in Onitsha during the dry season.
document_9089743_table_009.png	The table presents a comparison of per capita expenditure and income between tea and non-tea households, including the difference in means for both outcomes.
document_10069312_table_004.png	The table presents the results of a Tobit model analyzing the influence of various factors (e.g., tariffs, port efficiency, regulatory environments) on intra-African trade, including pooled cross-section and fixed effects for the year 2003.
document_10455617_table_006.png	The table presents a list of countries where surveys on government comments regarding services trade policies were conducted, along with whether government confirmation was received in 2008 and information collected from public sources.
document_11958451_figure_012.png	The figure presents data on Russia's oil revenue as a percentage of total general government revenues and the price of Russian oil from 1997 to 2007, alongside a separate depiction of oil dependence concerning export revenues from 1994 to 2007.
document_2160788_figure_001.png	The figure illustrates the projected adult HIV prevalence percentages over time for various scenarios involving a preventive HIV vaccine targeted at high-risk populations, compared to traditional interventions such as CSW and STI programs.
document_12736370_table_001.png	The table reports children's household and individual characteristics segmented by different survey assignments, including percentages for demographic factors and household-related metrics, along with an F-test assessing the equality of coefficients across groups.
document_10069312_table_000.png	The table presents summary statistics for various trade facilitation variables, including port efficiency, customs, regulatory measures, and services, for a whole sample and specifically for an African sample.
document_11225119_table_004.png	The table reports the projected changes in import prices for various sectors in Ethiopia under an EPA scenario, displaying both the import weighted average price change and the share of each sector in total imports.
document_6731296_figure_000.png	The histogram displays the distribution of blue collar shortages, measured as fractions, across various levels represented on the ZB axis.
document_9089743_table_003.png	The table presents the yields from tea cultivation, segmented by gender, across various estimation methods (Gauss, Epanechnikov, Quartic, Uniform, and Cosinus).
document_8092215_table_001.png	The table reports estimated coefficients and p-values for trade demand and supply elasticities related to non-fuel merchandise trade between Latin American and Caribbean countries and India, using different econometric models.
document_11867889_table_007.png	The table presents data on the least and most dynamic export products from Argentina during 2004-2007, including their share in total exports and the average annual growth rate.
document_11867889_figure_005.png	The figure presents net flows of various service sectors in Argentina from 1999 to 2007, illustrating trends in sectors such as communication, construction, financial, and government services.
document_1689472_figure_002.png	The figure presents frequency distributions of certainty equivalents for various investment and insurance decisions, outlining the fractions of respondents indicating various CE values.
document_2874487_table_004.png	The table reports OLS regression results measuring the effect of political affiliation on net loans from the central government to state governments, including variables related to political affiliation, state income, and population.
document_693460_table_001.png	The table reports the structure of the securities market in Estonia, detailing the percentage distribution of various categories of issuers and investors alongside key market indicators for the years 1995 and 1996.
document_6304708_table_002.png	The table reports changes in export and import prices for various sectors in Russia as a result of the Doha Round and Global Free Trade, expressed as ad-valorem percentages.
document_700615_table_005.png	The table presents econometric estimations related to import demand, showcasing dependent variables and their coefficients for different countries along with various statistical test results.
document_699791_figure_009.png	The figure illustrates the structure of public bonds in Mexico from June 1987 to June 1990, indicating the amounts in thousands of pesos and categorizing them into various types of bonds.
document_2160788_table_002.png	This table presents the cumulative number of vaccinations projected to be required for targeting high-risk groups in South India over a period from 1998 to 2033, with different scenarios represented for varying levels of high-risk group strategies.
document_8921763_figure_004.png	The figure shows the relationship between the perceived chance of infection and the number of new SARS cases reported the previous day in Hong Kong on select dates.
document_439628_table_008.png	The table summarizes the best models' statistics for macroeconomic vulnerability indicators in several Latin American countries, including unconditional probabilities, Type I and II errors, noise/signal ratios, and their performance metrics.
document_700561_table_001.png	The table reports monthly revenues, costs, and profits of tanker-truck water vendors in Onitsha, including breakdowns by tank size and seasonal variation in costs and revenues.
document_10455617_figure_005.png	The figure compares the services trade restrictiveness index across regions, including Uruguay Round commitments, Doha offers, and actual policies.
document_12916918_figure_006.png	The snapshot presents a figure illustrating the monthly price of coffee over time alongside monthly returns expressed as percentage changes, with indications of breaks identified by the KL (2000) test.
document_6213782_figure_002.png	The figure compares domestic and foreign ownership firms in relation to various business constraints, such as tax administration, cost of finance, electricity, transport, and access to land.
document_11308693_table_006.png	The table presents the coefficients for various factors influencing remitting behavior among migrants, categorized by education level, and includes observations from multiple countries.
document_6731296_table_006.png	The table presents estimated parametric adjustment functions for white collar, blue collar, and capital adjustments in Uruguayan manufacturing, highlighting the effects of positive shortages and the Mercosur trade agreement.
document_2160788_figure_002.png	The figure presents the projected cumulative number of vaccinations required for targeting the general population in South India over the years from 1998 to 2033.
document_9089743_table_000.png	The table presents average characteristics of tea growers in private and public sectors, including age, gender, land ownership, livestock ownership, and per capita expenditure, along with sample sizes.
document_438818_table_002.png	The table reports the mean share of ownership by various types of individual investors in firms across different years from 1992 to 1995, highlighting both bank-sponsored and non-bank sponsored investment funds.
document_8921763_figure_002.png	The graph displays the signals of macroeconomic vulnerability in Ecuador preceding its crisis, as derived from the Arima residuals model, showing fluctuations in index values over time.
document_439628_figure_000.png	The table presents results from different models assessing macroeconomic vulnerability, indicating Type I and Type II error rates, noise to signal ratios, and predictive capacity across several Latin American countries over the specified years.
document_439628_table_006.png	The table presents estimated parametric adjustment functions for white collar, blue collar, and capital adjustment in response to tariff changes, including coefficients for various factors such as shortages and interaction terms, as well as significance levels.
document_6731296_table_007.png	This table presents regression results analyzing the relationship between economic growth (measured by GDP per capita growth rate) and various banking sector indicators, including net interest margin, cost, and profit before tax as a share of total assets, across a sample of countries.
document_7095002_table_003.png	The figure shows the upper and lower bound estimates of percentage point increases in poverty for various countries in response to a 50% increase in food prices.
document_9899936_figure_000.png	The figure illustrates the relationship between log GDP per capita and total factor productivity (TFP) for various countries, indicating fitted values and showing Serbia highlighted in the data set.
document_6213782_figure_000.png	The figure displays projections of adult HIV prevalence percentages over time, comparing the impact of a preventive HIV vaccine targeted at the general population with other interventions such as targeting commercial sex workers (CSW) and sexually transmitted infection (STI) strategies.
document_2160788_figure_000.png	The table presents the results of linear probability models examining the relationship between pension eligibility, health status, and the likelihood of working at least one hour per week among adults over 45 in China, Indonesia, and Korea, differentiated by urban and rural settings and gender.
document_15347644_table_001.png	The table reports the top 10 exports from Argentina in 2007 and 1997, indicating their total export values, shares in total exports, main export destinations, and shares in world exports.
document_11867889_table_001.png	The figure presents the Trade Intensity Index of Argentina in relation to its main export partners, showing trends from 1992 to 2007.
document_11867889_figure_011.png	The figure illustrates the volumes of automobile and ICT exports and imports to partner countries, alongside the share of P&C (Partnership & Cooperation) for Brazil, the European Union, and the USA over specified years.
document_11867889_figure_018.png	The table reports the number of countries and the price elasticities from various studies, detailing both the number of positive elasticities and the average of negative elasticities.
document_700615_table_006.png	The figure presents scatter plots showing the relationship between changes in poverty headcount and initial poverty headcount for four West African countries: Ghana, Guinea, Niger, and Senegal.
document_9899936_figure_001.png	The snapshot presents data on trade and commerce (T&C), footwear, and furniture exports and imports for Argentina compared to other countries over the period from 1992 to 2006, indicating variations in trade shares and values.
document_11867889_figure_016.png	The histogram illustrates the distribution of white collar labor shortages among manufacturing firms in Uruguay, showing varying levels of shortages represented as fractions.
document_6731296_figure_001.png	The table presents child labor statistics comparing participation rates and hours worked for boys and girls, using different survey designs and reporting methods.
document_12736370_table_002.png	The table reports baseline characteristics of maternal and household traits in a treatment and comparison group, including maternal age, education level, marital status, number of pregnancies, household size, asset value, and utilization of prenatal care services.
document_11696987_table_003.png	The table presents estimates of net wealth, net oil wealth as a percentage of GDP, and the sustainable level of annual spending in terms of annuity for Russia's oil wealth as of 2009.
document_11958451_table_003.png	The figure shows the estimated size of fiscal stimulus measures as a percentage of GDP for various G-20 countries across the years 2008, 2009, and 2010.
document_11958451_figure_013.png	The table reports the restrictiveness of Uruguay Round commitments across various regions and service sectors, showing percentages for financial, telecom, retail, maritime, professional services, and an overall score for each region.
document_10455617_table_003.png	The table reports the effects of political affiliation on loans and advances made by state governments, including various statistical variables and their coefficients.
document_2874487_table_005.png	The table reports the revenue implications of a COMESA Common External Tariff for Malawi, Zambia, and Kenya, detailing old and new import, tariff, excise, and VAT revenue figures along with their changes and percentage changes.
document_11225119_table_001.png	The table presents trade demand and supply elasticities of GDP associated with China for various Latin American and Caribbean regions, showing estimated coefficients and p-values for own supply and China demand using different econometric models.
document_8092215_table_000.png	The table presents the results of a regression analysis measuring various factors that determine land values per acre, including land tenure types, trees per acre, soil conservation practices, and household characteristics.
document_6666871_table_005.png	The figure presents the frequency distributions of perceived SARS risk in Taiwan, highlighting three dimensions: fatal risk, knowledge, and controllability, measured across a scale from low to high perceptions.
document_8921763_figure_003.png	The figure presents the trends in domestic and foreign dollar interest rates expressed as annual percentages over a period from June 1987 to June 1990.
document_699791_figure_008.png	The table presents the results of a regression analysis estimating the average difference in per capita expenditure across various variables, including gender, age, education, household size, and market access.
document_9089743_table_010.png	The figure illustrates the number of structural breaks in commodity price volatility, categorized as 'Breaks UP' and 'Breaks DOWN' based on two tests (IT and KL) over a time span from before 1860 to 2000.
document_12916918_figure_002.png	The table reports the high-skilled emigrant stock in thousands and as a percentage of the population, alongside the total emigrant stock percentage and a governance indicator for various countries.
document_8066254_table_003.png	The figure presents baseline estimation of adjustment functions for white collar, blue collar, and capital employment in manufacturing firms, with all other shortages set to zero.
document_6731296_figure_004.png	The figure displays the adjustment functions for white collar employment before and after Mercosur trade agreements, showing two distinct curves representing the post Mercosur and pre Mercosur phases.
document_6731296_figure_008.png	The table lists various products alongside their Revealed Comparative Advantage (RCA) values for Argentina in 2007, indicating the relative advantage of exporting these products.
document_11867889_table_006.png	The table presents results from a regression analysis examining the interaction effects of being an oil exporter and ethnic fragmentation on the likelihood of conflict onset, across various country classifications.
document_7499620_table_003.png	The table provides estimates of import demand functions under rationing for various categories of goods in Morocco, including coefficients for domestic and imported goods, as well as labor and investment shares.
document_700615_table_002.png	The table compares various educational metrics (propensity score, head principal ratio, complete and monograde schools, student-teacher ratio, total enrollment) between schools with and without school-based management (SBM) across different quintiles.
document_11992660_table_002.png	The figure illustrates the adjustment functions for capital in the manufacturing sector under differing tariff conditions, comparing scenarios of no change, a 4 percent reduction, and a 2 percent reduction in tariffs.
document_6731296_figure_013.png	The figure presents the percentage of 47 African countries and 71 countries outside Africa that implemented various food price policies, including reducing foodgrain taxes, increasing foodgrain stocks, imposing export restrictions, and applying price controls or consumer subsidies.
document_9899936_figure_002.png	The table presents estimated coefficients and p-values from econometric analyses examining the impact of China's trade flows on non-fuel exports from Latin American and Caribbean countries to third countries, categorized by different regions.
document_8092215_table_002.png	The figure reports the number of banking crises that occurred in relation to the years following liberalization, showing a decline from 12 to 1 over a five-year period.
document_437731_figure_000.png	The table presents the regression estimates of the effects of school-based management interventions on school-averaged test scores in math, English, science, and overall composite scores, including various school characteristics and teacher-related factors.
document_11992660_table_006.png	The figure displays adjustment functions for capital, comparing pre and post Mercosur trade liberalization periods, showing how these adjustments are quantified in index values.
document_6731296_figure_010.png	The table presents a comparison of risk tolerance scores between non-contributing and contributing employees and self-employed individuals, along with statistical tests for differences in means.
document_1689472_table_005.png	The table reports probit estimates analyzing the relationship between financial liberalization, transparency, and the occurrence of bank crises, showing the significance and coefficients of various explanatory variables.
document_437731_table_003.png	The table presents regression results for the relative quality of new goods exported by OECD compared to Non-OECD countries, indicating the coefficients for various quantile regressions.
document_14435139_table_002.png	The figure presents the adjustment functions for white collar employment in relation to export levels, showing varying responses based on the proportion of sales derived from exports.
document_6731296_figure_017.png	The table reports mean characteristics of villages in a sample, including general demographics, income structure, governance, and knowledge about property law among village leaders and households.
document_8886604_table_000.png	The table presents projections for fiscal data and the size of fiscal adjustments in terms of non-oil total revenue and grants as well as non-oil primary expenditure and net lending for the years 2008 to 2017 under two scenarios of fiscal adjustment (temporary and sustained).
document_11958451_table_004.png	The figure displays a global map indicating tectonic plates and their associated earthquake activity, categorized by varying levels of seismic hazard.
document_11670035_figure_000.png	The table presents simple correlation coefficients between various economic indicators, including GDP per capita, interest margins, bank profit margins, and asset shares, measured in logarithmic values.
document_7095002_table_005.png	The table presents a comparison of per capita expenditure and income between tea and non-tea households, utilizing different kernel methods for matching analysis.
document_9089743_table_008.png	The table presents the global production of opium from various countries over selected years, detailing specific production amounts for each country.
document_9087385_table_003.png	The table presents the percentage of global seizures of cocaine and opiates by country in 2004, along with total weights in tons.
document_9087385_table_004.png	The figure compares the business constraints faced by exporters and non-exporters, specifically highlighting issues related to customs and trade regulations, transportation, access to land, and the skills and education of available workers.
document_6213782_figure_003.png	The figure presents the relationship between total household remittances and the years of schooling of the most educated migrant, showing a semi-parametric regression line along with confidence intervals.
document_11308693_figure_000.png	The figure displays the projected oil prices from 2007 to 2012, with specific values noted for each year, indicating fluctuations over this period.
document_11958451_figure_018.png	The table reports the treatment effects of school-based management interventions on student test scores in math, English, science, and overall scores using different statistical methods including OLS, fixed effects, and Kernel-PSM.
document_11992660_table_005.png	The figure presents adjustment functions for blue collar employment, comparing pre and post Mercosur periods, illustrating the different adjustment dynamics in response to capital employment changes.
document_6731296_figure_009.png	The table presents mean and standard deviation estimates of the welfare impacts on Russian households resulting from WTO accession, reform of foreign direct investment barriers, and various trade scenarios, categorized by household income deciles.
document_6304708_table_005.png	The figure presents trends in gross exports and imports of Argentina, alongside its share in world exports and imports from 1992 to 2007.
document_11867889_figure_003.png	The figure illustrates the distribution of households by their monthly expenditure on water expressed as a percentage of total household income, comparing data for both the dry and rainy seasons.
document_700561_figure_005.png	The table presents coefficients from a regression analysis examining the interactions of various covariates with short survey modules and proxy reporting on children's labor force participation, specifically for boys and girls.
document_12736370_table_007.png	The table reports the cumulative percentage distribution of signals indicating macroeconomic vulnerability for various Latin American countries within a 24-month period leading up to a crisis, categorized by different time frames (3, 6, 12, 18, and 24 months).
document_439628_table_005.png	The figure presents an individual decision tree showing potential losses and subjective probabilities associated with taking or not taking protective actions during a threatened disease outbreak.
document_8921763_figure_001.png	The table presents estimated parametric adjustment functions for white collar, blue collar, and capital adjustments, including coefficients for various shortage parameters and their statistical significance.
document_6731296_table_004.png	The graph displays signals of macroeconomic vulnerability in Ecuador, showing two lines that represent different metrics, with a signal being flagged when one line exceeds the other. The data captures trends leading up to a identified crisis.
document_439628_figure_001.png	The figure illustrates the adjustment functions of capital across different export levels for manufacturing firms, with categories indicating no exports, 25% of sales from exports, and 50% of sales from exports.
document_6731296_figure_019.png	This table reports determinants affecting the compensation received by households who experienced land taking, analyzing variables such as reform implementation, land characteristics, village income, and leader knowledge related to land rights.
document_8886604_table_004.png	The table presents the coefficients relating to total remittances from migrants, segmented by education level and control variables such as income and family, across various countries.
document_11308693_table_005.png	The table reports data on the incidence of land takings in villages across China, detailing aspects such as the purpose of land takings, jobs generated, and compensation paid, broken down by region.
document_8886604_table_002.png	The table presents the main activities of boys and girls in child labor, comparing responses from short versus detailed survey questionnaires and proxy versus self-reported data.
document_12736370_table_003.png	The figure presents the average hours of work per week for older workers and the elderly across China, Indonesia, Korea, the USA, and the UK, broken down by urban and rural status as well as gender, under different work status conditions.
document_15347644_figure_003.png	The figure displays the level of real GDP in Russia from 2007 to 2019, comparing projections for 'after crisis' and 'before crisis' scenarios, highlighting the impact of the global crisis on the economy.
document_11958451_figure_019.png	The figure depicts the nominal interest rates on commercial bank loans in Estonia, showing trends for short-term and long-term interest rates from March 1994 to March 1998.
document_693460_figure_001.png	This table presents the results of non-parametric tests comparing time preferences between different groups, including waged/salaried employees and the self-employed, along with their associated p-values.
document_1689472_table_002.png	The table presents projected annual numbers of vaccinations in millions across different vaccination scenarios for the years 2008 to 2033.
document_2160788_table_003.png	The table presents key macroeconomic indicators for Russia from 2006 to 2009, including GDP growth, industrial production growth, inflation, current account balance, unemployment, oil prices, and reserves.
document_11958451_table_000.png	This chart displays the number of structural breaks in volatility for various commodities since the 1970s, categorized into two groups represented by different colors (KL and IT).
document_12916918_figure_003.png	The table presents average agricultural yields for various crops and milk production across several countries in Eastern and Central Europe from 1985 to 1988.
document_699976_table_001.png	The table reports the cumulative percentage distribution of signals that indicate macroeconomic vulnerability for various Latin American countries within different time frames leading up to a crisis.
document_439628_table_003.png	The table presents various measurements related to yield, fertilizer use, fertilizer cost, time to carry, and extension cost, showing calculations related to observable heterogeneity in these outcomes.
document_9089743_table_004.png	The figure illustrates expectations regarding unscheduled devaluation of the Mexican currency represented as annual percentages from June 1988 to June 1990, showing a decline over the observed period.
document_699791_figure_006.png	The figure presents the components of export growth in Argentina from 1995 to 2004, detailing increases and decreases in exports across various categories such as existing products to existing markets and new products to new markets.
document_11867889_figure_014.png	The table reports various indicators of tariff revenue sources in Ethiopia, including shares of imports, total tariff revenue, and trade weighted averages for different trading groups such as COMESA and EU27.
document_11225119_table_003.png	The table lists various products exported by Argentina, their main export partners, and competing nations for those products as of 2007.
document_11867889_table_005.png	The table presents statistical estimates from models analyzing the relationship between tourism arrivals and factors including lobbying, real exchange rate, and real GDP per capita, using various estimation methods.
document_10240515_table_000.png	The figure illustrates adjustment functions for white collar employment in the manufacturing sector under different tariff scenarios, including no change in tariffs, a 2 percent reduction, and a 4 percent reduction.
document_6731296_figure_011.png	The table reports various land rights and agricultural characteristics in Uganda, including the percentage of parcels sold, rented, and acquired through different means, as well as data on land value improvements and crop input usage.
document_6666871_table_000.png	The table reports long-run import demand elasticities for various countries, including income and price elasticity values along with their standard errors.
document_700615_table_001.png	The table reports the knowledge of male and female households regarding key provisions of land law in Uganda, showing percentages of awareness and understanding related to customary ownership, eviction protections, and application processes across different land tenure types.
document_6666871_table_002.png	The figure presents the monthly price data for soybeans and the monthly returns expressed as percentage changes, along with identified structural breaks in volatility detected by KL (2000) test.
document_12916918_figure_012.png	This table presents first-stage regression results examining the relationship between various factors, such as external asset positions and lobbying efforts, with respect to tourism lobbying activities in the Caribbean context.
document_10240515_table_004.png	The table reports cocaine production amounts for Bolivia, Colombia, and Peru over selected years from 1990 to 2004, including total production across these countries.
document_9087385_table_002.png	The table presents a statistical analysis of factors influencing the probability of self-employment and contributions to pension systems among self-employed and employed individuals in Chile, including coefficients for various demographic and economic variables.
document_1689472_table_006.png	The figure illustrates the long-term trends in Argentina's GDP per capita and its share of world exports. It displays GDP per capita in PPP US dollars alongside the total value of world exports and Argentina's percentage share of these exports over time.
document_11867889_figure_001.png	The table compares time preferences between contributing and non-contributing employees and self-employed individuals, showing the percentage for each group and the results of hypothesis tests regarding their time preferences.
document_1689472_table_003.png	The figure presents concentration curves that illustrate the distribution of coverage by Vietnam's Health Care Fund for the Poor among different populations, including those officially designated as poor and ethnic minorities in mountainous regions.
document_7368143_figure_000.png	The table reports the share of total rice consumption and the proportion of consumers for various countries in West and Central Africa, along with the share of rice consumed by the bottom 40% and 60% of the population.
document_9899936_table_000.png	The figure compares annual GDP growth rates and the overall budget balance as a percentage of GDP in Russia from 1995 to 2006, illustrating the relationship between fiscal surpluses and economic growth over the period.
document_11958451_figure_004.png	The figure presents a comparison of subjective discount rates for non-contributing and contributing employees and self-employed individuals, highlighting differences in preferences related to pension contributions.
document_1689472_figure_003.png	This table presents first-stage regression results analyzing the relationship between various economic and political indicators and revenue mobilization, focusing on aid and foreign resource exports from 1999 to 2005.
document_10002285_table_002.png	The table categorizes service policies using a 5-point scale from open without restrictions to completely closed, along with corresponding descriptions and commitments from the Uruguay Round and Doha offers.
document_10455617_table_004.png	The snapshot displays the monthly price of zinc over time along with the monthly returns expressed as percentage change and identified breaks using the KL (2000) test.
document_12916918_figure_015.png	The figure illustrates the annual real rate of return on AFP (Pension Fund Administrator) investments in Chile from 1981 to 2000, showing fluctuations over the years.
document_1689472_figure_007.png	The snapshot presents historical monthly prices of crude petroleum alongside the monthly returns expressed as percentage change, including detected breaks in volatility as indicated by the KL (2000) test.
document_12916918_figure_008.png	The table presents results from a logit model analyzing various factors affecting per capita expenditure, including demographic and asset variables.
document_9089743_table_001.png	The table reports quantities of various exported motor vehicle parts and other goods from Argentina, including specific quantities and the respective export destinations.
document_11867889_table_003.png	The table presents estimated parametric adjustment functions related to the impact of export share on sales, measuring the effect of various shortages (white collar, blue collar, and capital) on the adjustment processes in manufacturing firms.
document_6731296_table_009.png	The table reports the daily revenues, costs, and net revenues of a water distribution vendor in Onitsha during the rainy and dry seasons, including quantities sold and prices charged.
document_700561_table_003.png	The table reports the effects of school-based management (SBM) interventions on school-averaged test scores in math, English, and science, comparing post-intervention results and various school characteristics.
document_11992660_table_008.png	The table presents the restrictiveness levels of Doha offers by region across various service sectors, including Financial, Telecom, Retail, Maritime, and Professional, with overall restrictiveness scores for each region and globally.
document_10455617_table_002.png	The table details revenues and costs of a small retail water vendor in Onitsha, highlighting quantities sold, pricing, costs of water, and net revenues for both rainy and dry seasons.
document_700561_table_002.png	The table presents data on average firm ownership shares by sponsor type, concentration indicators, and firm performance indicators, detailing trends and statistics over several years.
document_438818_table_000.png	The figure presents employment patterns and access to pensions for older workers in urban and rural areas across China, Indonesia, and Korea, comparing the ratios of pension-eligible individuals to total working individuals by age group.
document_15347644_figure_004.png	The figure presents the composition of Argentina's GDP by sector (Agriculture, Industry, Services) over time from 1965 to 2005, showing the relative contributions of each sector as a percentage of total GDP.
document_11867889_figure_000.png	The table presents results from balancing tests comparing differences in various educational grades, regions, and characteristics before and after matching in a statistical analysis, including average differences and percentages of change due to matching.
document_7368143_table_004.png	The figure displays the proportion of firms encountering constraints related to the cost of financing, business licensing and operating permits, and the skills and education of available workers, categorized by ownership type: denovo, privatized, and state/social.
document_6213782_figure_001.png	The snapshot displays data on net private capital inflows, including errors and omissions, and net foreign direct investment (FDI) in Russia from 1994 to 2007, indicating trends in private capital flows and direct investment.
document_11958451_figure_011.png	The table reports coefficients for various factors affecting total suspended solids (TSS) and chemical oxygen demand (COD) in water pollution, including inspection rates, industry types, and other variables.
document_438376_table_001.png	The figure shows the share of exports from various Latin American and Caribbean countries to China and India in 1990 compared to 2004.
document_8092215_figure_001.png	This table reports the difference-in-difference estimates of the effects of school-based management (SBM) interventions on average test scores in math, English, science, and overall performance, across various school characteristics.
document_11992660_table_007.png	The figure presents the growth rates of total exports, primary products, and agriculture manufacture in Argentina from 1991 to 2007, based on value, price, and quantity metrics.
document_11867889_figure_004.png	The figure depicts the adjustment functions for blue collar employment across different export statuses, showing how various levels of export activity correlate with employment adjustment patterns.
document_6731296_figure_018.png	This figure illustrates employment rates by age cohort for older workers in China, Indonesia, Korea, the UK, and the US, differentiating by urban and rural status as well as gender.
document_15347644_figure_001.png	The table presents regression analysis results examining risk tolerance using certainty equivalents from various decision-making scenarios. It includes coefficients and standard errors for fixed and random effects, alongside demographic variables such as income, education, gender, rural status, and marital status.
document_1689472_table_001.png	The table presents data on the incidence of land reallocations in Chinese villages, detailing the share of villages affected, average land reallocations before and after a legal reform, and areas affected by reallocations, categorized by region.
document_8886604_table_001.png	The table presents unconditional test score means for math, science, and English, comparing school-based management (SBM) and non-SBM groups across the years 2002 and 2004. It includes differences in scores and t-statistics for statistical significance.
document_11992660_table_004.png	This table presents results from a Tobit model analyzing factors affecting trade within Africa, reporting coefficients and standard errors for various trade-related indicators across pooled data and fixed effects for the year 2003.
document_10069312_table_005.png	The table presents key household characteristics in Uganda, including demographics, knowledge of land law, assets, income sources, and engagement in various economic activities segmented by quartiles of asset distribution.
document_6666871_table_001.png	The figure displays the interbank interest rates in Estonia, specifically the TALIBOR rates over various time periods, including 1 week, 1 month, and 3 months, from January 1996 to November 1997.
document_693460_figure_002.png	The table shows changes in expenditure for different income groups in Mauritius before and after tariff reforms, including old and new expenditure values and the percentage change in expenditure.
document_11225119_table_009.png	The table presents information on diaspora bonds issued by India, including bond types, amounts raised, years of issuance, maturity periods, minimum investment requirements, and coupon rates.
document_8066254_table_002.png	The table reports tariff rates, export tax rates, estimated changes in export prices from WTO accession, and equivalent barriers to foreign direct investment (FDI) by sector.
document_6304708_table_001.png	The figure presents trends in public debt, distinguishing between domestic and foreign currency denominated debt, alongside the evolution of real GDP from 1990 to 2008.
document_11958451_figure_000.png	The figure displays a chart indicating signals of macroeconomic vulnerability in Mexico leading up to a crisis, with values represented on a scale from -1 to 3 over a specified time period.
document_439628_figure_005.png	The table presents descriptive statistics on health insurance status and determinants for households, including the prevalence of various types of insurance and attributes of household heads such as education and age.
document_7368143_table_001.png	The table presents results from robustness tests assessing the impact of various forms of earthquake propensity on annual deaths, categorized by different models. Each model analyzes the propensity in different country contexts (e.g., developing vs. developed, democracies vs. autocracies).
document_11670035_table_001.png	The table presents descriptive statistics for various characteristics of older workers from China, Indonesia, and Korea, including work status, education, pension eligibility, and family structure.
document_15347644_table_000.png	The figure illustrates the share of Argentina's exports categorized by product group and destination for the periods January to September 2007 and 2008, showcasing changes in export composition over time.
document_11867889_figure_007.png	The figure shows the average inflation rate in Mexico, measured as the percentage change in the Consumer Price Index (CPI), over the years from 1980 to 1991.
document_699791_figure_004.png	The table presents the estimated impacts of various trade policy scenarios, including WTO accession and Doha Agenda completion, on aggregate welfare, government budget, aggregate trade, and returns to mobile factors in Russia.
document_6304708_table_004.png	This figure presents combined measures of various components of the investment climate across all 26 transition countries and specifically for Serbia, comparing aspects such as infrastructure, regulation, property rights, finance, taxation, and macroeconomic factors.
document_6213782_figure_005.png	The table reports the revenue implications of an Economic Partnership Agreement (EPA) for Tanzania, Kenya, and Ethiopia, detailing old and new import values, tariff revenues, excise revenues, VAT revenues, total revenues, and changes in these values.
document_11225119_table_002.png	The snapshot presents a comparative analysis of the restrictiveness of GATS (Uruguay Round) commitments, Doha offers, and actual policy for various countries, plotted against GDP per capita in purchasing power parity (PPP) for the year 2006.
document_10455617_figure_004.png	The table presents regression results linking foreign bank share to banking sector efficiency, measuring variables such as net interest margin, profit before tax, and macroeconomic indicators across multiple countries during 1994-2003.
document_7095002_table_002.png	The figure shows the trend of foreign exchange reserves in Russia expressed as a percentage of GDP from 1997 to 2007.
document_11958451_figure_008.png	The table reports projected changes in tariff revenue and total trade tax revenue in response to the elimination of all tariffs on imports from the EU for selected countries, based on different tariff calculations.
document_11225119_table_000.png	The graph illustrates the signal of macroeconomic vulnerability in Brazil, using a chartist model, with values displayed over a multi-year period.
document_439628_figure_003.png	The table presents regression results comparing new goods and incumbent goods with emphasis on the impact of OECD status on export quality dynamics, with values reported for different quantiles.
document_14435139_table_003.png	The table reports the coefficients from a regression analysis examining the relationship between education and remittances for migrants across various countries, with specific breakdowns by university degree and years of schooling.
document_11308693_table_007.png	The table presents a regression analysis of subjective discount rates based on responses to hypothetical questions about time preferences, including various factors such as income, education, and demographic characteristics.
document_1689472_table_000.png	The table presents the results of an OLS regression analyzing various factors affecting trade, including tariffs and port efficiency, with coefficients and standard errors reported for different model specifications.
document_10069312_table_003.png	The figure compares the percentage decrease in capital flows and terms of trade due to oil shocks for the years 1998-99 and 2008-09.
document_11958451_figure_006.png	The figure presents adjustment functions for blue collar employment across different tariff levels (10%, 20%, and 30%), showing how employment adjusts in response to changes in trade protection.
document_6731296_figure_016.png	This figure illustrates the adjustment functions for blue collar employment in relation to different tariff reduction scenarios in the manufacturing sector, comparing cases with no change in tariff, a 2 percent reduction, and a 4 percent reduction.
document_6731296_figure_012.png	This figure shows the annual total bond sales in million dollars in Israel from 1996 to 2003, illustrating an upward trend over the years.
document_8066254_figure_000.png	This figure illustrates the distribution of bond sales in Israel from 1951 to 2003, categorized into fixed rate and floating rate bonds, along with notes, presented as percentages of total bond sales.
document_8066254_figure_001.png	The figure presents the growth rates of imports categorized by value, price, and quantity over the years 1987 to 2007, indexed to the year 1993.
document_11867889_figure_006.png	The table presents descriptive statistics for student performance and school characteristics across all schools, those with school-based management (SBM), and non-SBM schools for the years 2002, 2003, and 2004. It includes average test scores for subjects such as math, English, and science, as well as other metrics like total enrollment and dropout rates.
document_11992660_table_000.png	The table presents a statistical model assessing factors influencing participation in the tea sector, reporting coefficients, standard errors, z-statistics, and probabilities for various variables such as age, education, and household characteristics.
document_9089743_table_006.png	The figure presents the adjustment functions related to capital across different tariff levels (10%, 20%, and 30%) for manufacturing sectors, showing varying degrees of adjustment efficiency.
document_6731296_figure_015.png	The table lists several surveys related to migrants, detailing the year conducted, sample size, and specific populations targeted within those surveys.
document_11308693_table_001.png	The table reports the distribution of households covered and not covered by the Health Care Fund for the Poor (HCFP), divided into trimmed and not trimmed samples.
document_7368143_table_003.png	The table presents estimated coefficients for various adjustment functions related to white collar, blue collar, and capital employment based on tariff levels and shortages in Uruguay's manufacturing sector.
document_6731296_table_008.png	The table reports the total number of banks, the total number of foreign banks, and the asset share of foreign banks as a percentage of total assets for various countries from 1994 to 2003.
document_7095002_table_000.png	The table reports the results of regression analyses examining the relationship between various variables (such as years of education, income, and household factors) and remittance behavior among migrants, including total remittances and extensive and intensive remittance measures.
document_11308693_table_004.png	The figure presents the Real Effective Exchange Rate (REER) for Russia, indexed to the year 1995, showing trends over time.
document_11958451_figure_001.png	The figure displays the trends in non-oil primary fiscal balance, oil revenue, and Russian oil price from 1997 to 2007, indicating fluctuations in fiscal performance relative to oil market changes.
document_11958451_figure_010.png	The table presents summary statistics for various fiscal and political variables across 360 observations from Indian states, including political affiliation, real state income, fiscal deficits, and spending metrics.
document_2874487_table_000.png	The table reports annual prevalence estimates of cocaine abuse by region, indicating both the number of people affected and the corresponding percentage of the population over 15 years old.
document_9087385_table_001.png	The histogram presents the distribution of capital shortages among manufacturing firms in Uruguay, measured in terms of a variable labeled 'ZK', expressed as a fraction.
document_6731296_figure_002.png	The figure compares the economic recovery trajectories of Russia during the crises of 1998-99 and 2008-09, highlighting a slower recovery in the latter period as indicated by the plotted trends.
document_11958451_figure_005.png	The table reports the exports and imports of selected agricultural and industrial products for the year 1999, detailing specific commodities along with their corresponding trade values.
document_9087385_table_006.png	The table presents the unconditional probabilities of economic crises in various Latin American and Caribbean countries over two sample periods: 1980-1998 and 1986-1998.
document_439628_table_002.png	The table reports the number of firms, mean values of Q (market valuation) with standard deviations, and mean profit with standard deviations for various sectors in the Czech Republic from 1992 to 1995.
document_438818_table_003.png	The figure depicts adjustment functions for white collar employment, displaying different trends based on tariff levels of 10%, 20%, and 30%.
document_6731296_figure_014.png	The figure presents data on automobile and ICT exports and imports between Argentina and comparators, showing both volume in US$ million and market share over the period from 1992 to 2006.
document_11867889_figure_017.png	The table reports estimates of the impact of the Health Care Fund for the Poor on various out-of-pocket payments and healthcare utilization indicators among beneficiaries compared to nonbeneficiaries.
document_7368143_table_005.png	The table reports the projected economic impacts of trade diversion and trade correction in response to an Economic Partnership Agreement (EPA), detailing wins, losses, and net values for various regions including ECOWAS, Africa, EU, USA, China, and a total.
document_11225119_table_010.png	The table presents coefficients from ordinary least squares (OLS) and Heckman models explaining the relative concentration of high-skill versus low-skill migrants, including variables such as lagged diaspora, colonial links, language, and distance.
document_14491760_table_002.png	The table presents results of regression models estimating the relationship between earthquake propensity and annual sum of earthquake deaths, including various factors such as country income and governance.
document_11670035_table_000.png	The figure presents Foreign Direct Investment (FDI) flows expressed as a ratio to GDP for Argentina, Brazil, and Chile alongside the total direct investment in Argentina for the years 1992 to 2007.
document_11867889_figure_002.png	The table presents the restrictiveness of actual services policies across different regions and sectors, measuring percentages for financial, telecom, retail, maritime, professional services, and an overall average.
document_10455617_table_001.png	The table reports estimates of health care fund impacts on various expenditures and healthcare utilization metrics among different consumption deciles. It includes measures such as out-of-pocket payments, inpatient expenses, and the frequency of outpatient visits.
document_7368143_table_008.png	The figure presents the ratio of tourism receipts to GDP for various Caribbean countries in 2001, illustrating the contribution of tourism to the economies of these nations.
document_10240515_figure_000.png	The table presents regression analysis results evaluating the relationship between various factors, including aid and fuel exports, and the efficiency of revenue mobilization for the year 2006, with a focus on data from 1999 and 1999-2005.
document_10002285_table_001.png	The table presents logistic regression results measuring the effects of various independent variables on the likelihood of conflict onset in non-democratic countries, comparing all non-democracies and poor non-democracies.
document_7499620_table_002.png	The table summarizes various datasets related to migrant populations, including the year of data collection, number of observations, and specific populations involved in each study.
document_11308693_table_000.png	The table presents logistic regression results examining various factors influencing the onset of conflict, including the age of the largest political party, years of elections, economic indicators like income per capita, and measures of ethnic and religious fractionalization.
document_7499620_table_000.png	The table presents regression analysis results showing the impact of diaspora on the selection of migrants, indicating coefficients for various predictors in relation to high-skill/low-skill migration ratios alongside statistical significance levels.
document_14491760_table_001.png	The snapshot displays the percentage of commodities identified as having at least one structural break in volatility, according to two statistical tests (IT and KL), across different years from 1860 to 2000.
document_12916918_figure_001.png	The figure illustrates the inflation revenue as a percentage of GDP in Mexico from the years 1980 to 1990, showcasing variations across those years.
document_699791_figure_003.png	The table reports the determinants of illegal land reallocation at the village level, presenting coefficients from probit and Tobit models analyzing variables such as reform, leadership elections, land certification, and village income.
document_8886604_table_005.png	The table reports statistical estimates of growth in unit values of exports, differentiating between OECD and Non-OECD countries, including coefficients for various terms and observations counted.
document_14435139_table_001.png	The table presents average characteristics for tea and non-tea households, including age, education, household size, land area, and ownership of livestock and transport, along with sample sizes.
document_9089743_table_007.png	This table presents actual and predicted distributions of child labor participation in agriculture, domestic work, and non-work categories, segmented by boys and girls, based on different questionnaire designs.
document_12736370_table_005.png	The snapshot presents historical monthly price data for sugar along with monthly returns expressed as percentage change, including detected breaks in volatility from statistical tests.
document_12916918_figure_013.png	The figure shows the annual average consolidated domestic public debt in Mexico as a percentage of GDP from 1982 to 1990, categorized into debt types from bank finance and bonds.
document_699791_figure_001.png	The figure presents projected changes in tariff revenue and trade tax revenue resulting from reforms to special tariffs, indicated as a percentage change across different tariff cap scenarios.
document_11225119_figure_001.png	The figure depicts the primary fiscal balance as a percentage of GDP alongside oil prices over several years, showing the relationship between fiscal performance and oil price fluctuations in Mexico.
document_699791_figure_002.png	The graph presents the signals indicating macroeconomic vulnerability in Colombia, showing the behavior of two lines over time, where a signal is issued when one line exceeds the other.
document_439628_figure_004.png	The table presents baseline characteristics of health facilities in 2006, comparing treatment and comparison groups across various expenditures, budget shares, and staffing metrics.
document_11696987_table_002.png	This table reports on the offer improvement, offer gap, and binding gap of actual policies compared to Uruguay Round commitments and Doha offers across various regions and globally.
document_10455617_table_000.png	The figure presents trends in relative prices comparing public/private and controlled/managed sectors in Mexico from 1987 to 1991, indicating fluctuations over the specified years.
document_699791_figure_005.png	The figure presents the restrictiveness of services trade policies categorized by mode (cross border, commercial presence, temporary movement of people) across various regions.
document_10455617_figure_003.png	The table presents statistical results for macroeconomic vulnerability indicators across several Latin American countries, including values for Type I and Type II error rates, noise-to-signal ratios, and performance measures over the specified period.
document_439628_table_001.png	The table presents probit regression results, detailing the effects of various factors such as poverty status, ethnicity, consumption, education level, and geographic region on health care access for both the full sample and households eligible for the Health Care Fund for the Poor.
document_7368143_table_002.png	The figure presents distributions of estimated welfare gains as a percentage of consumption from WTO accession, global free trade, and the Doha Agenda, based on a sample of 55,098 households.
document_6304708_figure_002.png	The table provides estimates of opiate abuse prevalence, highlighting the number of persons affected in millions and the corresponding percentage of the population over 15 for various regions.
document_9087385_table_000.png	The table presents the results of a regression analysis examining the relationship between various indicators of the banking sector (such as foreign bank asset share and profit before tax) and the growth rate of GDP per capita over the period from 1994 to 2003.
document_7095002_table_001.png	The table reports AR(1) coefficients and results from the Breusch-Pagan ARCH test for selected commodities, indicating their volatility characteristics and statistical significance.
document_12916918_table_000.png	The table reports the import content, total exports, and the percentage of imported intermediate content for various sectors of the Argentinean economy for the year 1997.
document_11867889_table_002.png	The figure illustrates the evolution of the number of zeros (indicating absence of trade) in Argentina's exports across various trading partners from 1990 to 2005. Changes in these values represent fluctuations in the number of products not traded.
document_11867889_figure_013.png	The figure presents the restrictiveness of services trade policies across different regions and sectors, comparing financial, telecommunications, transportation, and professional services.
document_10455617_figure_001.png	The table presents the results of an analysis on the determinants of air pollution, showing coefficients for various factors alongside their associated p-values, with significance levels indicated.
document_438376_table_002.png	The table presents regression results comparing export unit values between OECD and non-OECD countries, including relative quality and growth rates, along with number of observations.
document_14435139_table_000.png	The table presents simple correlation coefficients between various trade-related indicators, showing relationships for both intra-African trade and global trade samples.
document_10069312_table_002.png	The table reports the average prices charged by various water vendors in Onitsha, Nigeria, during the rainy and dry seasons, detailing prices for private boreholes, tanker trucks, small retail water vendors, and distributing vendors.
document_700561_table_000.png	The table reports the top 10 imports to Argentina for the years 2007 and 1997, including import values in US dollars, shares of total imports, main destination countries for each product, and share of world imports.
document_11867889_table_000.png	The figure presents data on export sophistication in Argentina compared to other countries from 1975 to 2000, depicting trends in GDP per capita (GDPpc), export sophistication index (EXPY), and a ratio of export sophistication to GDP per capita (EXPY/GDPpc).
document_11867889_figure_015.png	The figure compares certainty equivalents between non-contributing employees, non-contributing self-employed, contributing employees, and contributing self-employed individuals, indicating differences in preferences regarding pension fund contributions.
document_1689472_figure_005.png	The table presents the results of logistic estimations examining the effects of various factors on the onset of conflict in poor countries, including characteristics like the age of the largest party, years of elections, income per capita, and measures of ethnic and religious fractionalization.
document_7499620_table_001.png	The table presents a test of correlation between different instrument sets and errors for various countries, listing the correlation coefficients for each instrument set for each country.
document_700615_table_003.png	This figure shows the distributions of estimated welfare gains for Russian households resulting from the Doha agenda, comparing all households, the poorest decile, and the richest decile.
document_6304708_figure_003.png	The table presents the results of a regression analysis measuring the effect of political affiliation on state fiscal deficit, including variables such as political party alignment with the central government, coalition government status, state election years, and real fiscal deficit per capita among others.
document_2874487_table_002.png	The table presents regression results examining the determinants of transfer rights related to land in Uganda, comparing the influence of various factors on rights with and without approval.
document_6666871_table_006.png	The table lists specific tariff rates for various products in Tanzania, showing tariffs as a percentage or a fixed USD amount per metric ton, bag, or kilogram.
document_11225119_table_007.png	The figure presents the monthly price of wheat over time, along with the monthly returns expressed as percentage changes and identified breaks in volatility as per the KL (2000) test.
document_12916918_figure_014.png	The snapshot presents a time series of cocoa prices and monthly returns, indicating price volatility and structural breaks as detected by statistical tests.
document_12916918_figure_005.png	The table contains data on various types of healthcare facilities (provincial, central, other government hospitals, private providers, and traditional healers) and reported values indicating service utilization and associated statistics.
document_7368143_table_009.png	The figure shows the distributions of estimated welfare gains from Russian WTO accession, detailing the impact on all households, the poorest decile, and the richest decile, with values expressed as a percentage of consumption.
document_6304708_figure_001.png	The table presents total factor productivity (TFP) regression coefficients for various factors affecting firms in the manufacturing and services sectors, utilizing data from multiple country surveys.
document_6213782_table_001.png	The figure presents individual certainty equivalents for employees and self-employed individuals, potentially highlighting differences in risk and time preferences between these groups.
document_1689472_figure_006.png	The table provides a breakdown of sectoral weights for various service sectors, including banking, insurance, retailing, telecommunications, maritime shipping, and professional services, along with their modal weights and standardized sector weights for an average industrialized country.
document_10455617_table_005.png	The figure presents the residuals from an AR(1) model applied to selected commodity prices, specifically for copper, corn, sugar, and wheat, showing the difference between actual and fitted values over time.
document_12916918_figure_000.png	The figure presents a comparison of actual and expected devaluation rates based on a survey conducted by INEGI, illustrating trends over several quarters.
document_699791_figure_007.png	The figure presents trends in commercial bank borrowing and net borrowing of corporations in Russia from 1994 to 2007, indicating a significant increase in both types of borrowing over the years.
document_11958451_figure_014.png	The table presents results from a regression analysis using non-linear least squares, detailing coefficients, standard errors, t-statistics, and various statistical measures over the specified sample period.
document_699791_table_001.png	The snapshot displays the monthly price of copper and its monthly returns, including detected breaks in volatility as per KL (2000) test.
document_12916918_figure_007.png	The figure illustrates the relationship between GDP growth and unit value growth for various countries in the 1990s, highlighting a positive correlation.
document_14435139_figure_000.png	The table presents household characteristics categorized by survey assignment, detailing variables such as head's gender, age, educational years, household size, asset ownership, and more, along with F-tests for equality of coefficients across groups.
document_12736370_table_000.png	The figure presents propensity score histograms showing the probability of having a health card or health insurance for the poor, comparing those covered and not covered by the Health Care Fund for the Poor (HCFP) in both the full sample and the eligible subsample.
document_7368143_figure_001.png	The figure illustrates the trend in the average number of 'zeros' per partner in trade for Argentina compared to other regions such as Latin America, Industrialized, and East Asian countries from 1990 to 2005.
document_11867889_figure_012.png	This table presents the results of a non-linear least squares estimation for a compensation function, including coefficients for parameters w0 and w1, along with standard errors, R-squared values, and the number of observations.
document_6731296_table_002.png	The table presents summary statistics for various measures related to revenue mobilization, aid, exports, GDP, political rights, and population for a sample of 110 countries.
document_10002285_table_000.png	The figure displays the percentage of households in Onitsha categorized by their monthly expenditure on water during the rainy and dry seasons.
document_700561_figure_004.png	The figure displays frequency distributions for subjective discount rates related to time preference decisions, comparing responses based on spontaneous answers and post-probing for different time scenarios.
document_1689472_figure_001.png