In [1]:
import glob
import pandas as pd

# Load files

In [2]:
files = glob.glob("data/results_*.jsonl")
files

['data/results_refugee.jsonl']

In [3]:
df = pd.concat([pd.read_json(x, lines=True) for x in files]).reset_index(drop=True)
df

,snapshot_id,source,model,raw_output,usage,cost,status,incomplete_details,parsed_output,error
0,134_PAD7340ARABIC00n0220020140Arabic01_figure_...,refugee,gpt-5.5,"{""fields"":[{""metadata_field"":""snapshot_type"",""...","{'input_tokens': 13034, 'input_tokens_details'...","{'input_tokens': 13034, 'output_tokens': 1924,...",completed,NaN,{'fields': [{'metadata_field': 'snapshot_type'...,NaN
1,197_multi-page_table_004.png,refugee,gpt-5.5,"{""fields"":[{""metadata_field"":""snapshot_type"",""...","{'input_tokens': 13318, 'input_tokens_details'...","{'input_tokens': 13318, 'output_tokens': 2054,...",completed,NaN,{'fields': [{'metadata_field': 'snapshot_type'...,NaN

# Cost

In [4]:
df = df.join(pd.json_normalize(df["cost"]))

total = df["total_cost_usd"].sum()
mean = df["total_cost_usd"].mean()
std = df["total_cost_usd"].std()

print(f"Total cost: ${total:.2f}")
print(f"Ave cost per snapshot: ${mean:.4f}")
print(f"Std dev: ${std:.4f}")

Total cost: $0.25
Ave cost per snapshot: $0.1256
Std dev: $0.0038

In [5]:
df.groupby("source").agg(
    count=("source", "count"),
    total_cost_usd=("total_cost_usd", "sum"),
)

         count  total_cost_usd
source
refugee      2          0.2511

# Raw output

In [20]:
df.loc[0, "raw_output"]

'{"fields":[{"metadata_field":"snapshot_type","observed_value":"Figure","description":"The type of data snapshot, such as figure, table, map, or chart.","source_level":"snapshot","discovery_value":"high","reasoning":"Identifying the snapshot as a figure supports filtering, cataloging, and applying figure-specific metadata fields such as visualization type, legend categories, and data labels."},{"metadata_field":"figure_number","observed_value":"شكل 1","description":"The sequential number or identifier assigned to the figure within the document.","source_level":"snapshot","discovery_value":"medium","reasoning":"Figure numbering supports citation, cross-referencing, and locating the figure within the source document."},{"metadata_field":"figure_title","observed_value":"مصادر القروض في الأردن (2013)","description":"The title or caption text describing the subject of the figure.","source_level":"snapshot","discovery_value":"high","reasoning":"The figure title contains key searchable concepts including loan sources, Jordan, and the year 2013, which are important for discovery beyond document-level metadata."},{"metadata_field":"visualization_type","observed_value":"Pie chart","description":"The chart or visualization form used to present the data.","source_level":"snapshot","discovery_value":"medium","reasoning":"Knowing that the figure is a pie chart helps users understand that the data represent proportional shares across categories and supports visualization-based filtering."},{"metadata_field":"indicator_name","observed_value":"Sources of loans","description":"The main measured concept or indicator represented by the figure.","source_level":"snapshot","discovery_value":"high","reasoning":"The indicator is more specific than the document-level project metadata and enables retrieval of figures about credit sources or loan financing patterns."},{"metadata_field":"geographic_scope","observed_value":"Jordan","description":"The country, region, or place to which the figure data apply.","source_level":"both","discovery_value":"high","reasoning":"The snapshot title explicitly refers to Jordan, and the document metadata also identifies Jordan as the reference country; this field supports geographic filtering and aggregation."},{"metadata_field":"time_period","observed_value":"2013","description":"The year or period covered by the data in the figure.","source_level":"snapshot","discovery_value":"high","reasoning":"The figure title includes 2013, which is essential for temporal search, comparison, and analytical reuse."},{"metadata_field":"unit_of_measure","observed_value":"نسبة مئوية","description":"The measurement unit used for the displayed values.","source_level":"snapshot","discovery_value":"high","reasoning":"The unit indicates that the values are percentages, which is necessary for interpreting and reusing the data correctly."},{"metadata_field":"category_dimension","observed_value":"Loan source type","description":"The categorical dimension used to divide the data values in the figure.","source_level":"snapshot","discovery_value":"high","reasoning":"The pie chart categories represent different sources of loans, a reusable dimension useful for discovery of figures organized by financing source or provider type."},{"metadata_field":"category_labels","observed_value":"مؤسسة مالية رسمية؛ الأسرة أو الأصدقاء؛ جهة إقراض خاصة غير رسمية","description":"The category names or legend labels used in the figure.","source_level":"snapshot","discovery_value":"high","reasoning":"Category labels expose substantive information not necessarily captured in document-level metadata, enabling searches for formal financial institutions, family or friends, and informal private lenders."},{"metadata_field":"category_values","observed_value":"77؛ 6؛ 17","description":"The numeric values associated with the figure categories.","source_level":"snapshot","discovery_value":"medium","reasoning":"Capturing category values supports analytical reuse and allows users to discover figures containing quantitative distributions, although the labels are needed for full interpretation."},{"metadata_field":"category_value_pairs","observed_value":"مؤسسة مالية رسمية: 77؛ الأسرة أو الأصدقاء: 6؛ جهة إقراض خاصة غير رسمية: 17","description":"The pairing of category labels with their corresponding numeric values.","source_level":"snapshot","discovery_value":"high","reasoning":"Pairing labels and values makes the chart data directly reusable and searchable, preserving the semantic meaning of each percentage."},{"metadata_field":"source_citation","observed_value":"المصدر: دراسة استقصائية لمناخ الاستثمار (2012).","description":"The cited data source or provenance statement shown with the figure.","source_level":"snapshot","discovery_value":"high","reasoning":"The source citation supports provenance tracking and helps users assess the origin and credibility of the figure data."},{"metadata_field":"data_source_name","observed_value":"دراسة استقصائية لمناخ الاستثمار","description":"The named survey, dataset, report, or source from which the figure data were derived.","source_level":"snapshot","discovery_value":"high","reasoning":"A structured data source name enables discovery of figures based on common source datasets or surveys, such as investment climate surveys."},{"metadata_field":"data_source_year","observed_value":"2012","description":"The year associated with the cited data source, if distinct from the figure data period.","source_level":"snapshot","discovery_value":"medium","reasoning":"The source citation includes 2012, which may be useful for provenance and version tracking, especially because it differs from the 2013 year in the figure title."},{"metadata_field":"language","observed_value":"Arabic","description":"The language used in the figure or source document.","source_level":"both","discovery_value":"medium","reasoning":"The snapshot text is in Arabic and the document metadata lists Arabic; language metadata supports multilingual search, translation workflows, and language-based filtering."},{"metadata_field":"document_title","observed_value":"Jordan - Enhancing Governance and Strengthening the Regulatory and Institutional Framework for Micro, Small, and Medium Enterprise (MSME) Development Project","description":"The title of the source document containing the figure.","source_level":"document","discovery_value":"medium","reasoning":"Linking the figure to the source document title supports provenance, contextual discovery, and retrieval of the complete document."},{"metadata_field":"document_type","observed_value":"Project Appraisal Document","description":"The type or genre of the source document.","source_level":"document","discovery_value":"medium","reasoning":"Document type supports filtering figures by publication context, such as project appraisal documents versus analytical reports."},{"metadata_field":"project_id","observed_value":"P147875","description":"The project identifier associated with the source document.","source_level":"document","discovery_value":"high","reasoning":"Project identifiers allow figures to be linked to World Bank projects and support retrieval across related project documents."},{"metadata_field":"sector","observed_value":"Financial Sector","description":"The sector classification assigned to the source document or project.","source_level":"document","discovery_value":"medium","reasoning":"Sector metadata supports domain-level filtering and helps connect the loan-source figure to broader financial sector content."}]}'

# Parsed output

In [19]:
df.loc[0, "parsed_output"]["fields"]

[{'metadata_field': 'snapshot_type',
  'observed_value': 'Figure',
  'description': 'The type of data snapshot, such as figure, table, map, or chart.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'Identifying the snapshot as a figure supports filtering, cataloging, and applying figure-specific metadata fields such as visualization type, legend categories, and data labels.'},
 {'metadata_field': 'figure_number',
  'observed_value': 'شكل 1',
  'description': 'The sequential number or identifier assigned to the figure within the document.',
  'source_level': 'snapshot',
  'discovery_value': 'medium',
  'reasoning': 'Figure numbering supports citation, cross-referencing, and locating the figure within the source document.'},
 {'metadata_field': 'figure_title',
  'observed_value': 'مصادر القروض في الأردن (2013)',
  'description': 'The title or caption text describing the subject of the figure.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'The figure title contains key searchable concepts including loan sources, Jordan, and the year 2013, which are important for discovery beyond document-level metadata.'},
 {'metadata_field': 'visualization_type',
  'observed_value': 'Pie chart',
  'description': 'The chart or visualization form used to present the data.',
  'source_level': 'snapshot',
  'discovery_value': 'medium',
  'reasoning': 'Knowing that the figure is a pie chart helps users understand that the data represent proportional shares across categories and supports visualization-based filtering.'},
 {'metadata_field': 'indicator_name',
  'observed_value': 'Sources of loans',
  'description': 'The main measured concept or indicator represented by the figure.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'The indicator is more specific than the document-level project metadata and enables retrieval of figures about credit sources or loan financing patterns.'},
 {'metadata_field': 'geographic_scope',
  'observed_value': 'Jordan',
  'description': 'The country, region, or place to which the figure data apply.',
  'source_level': 'both',
  'discovery_value': 'high',
  'reasoning': 'The snapshot title explicitly refers to Jordan, and the document metadata also identifies Jordan as the reference country; this field supports geographic filtering and aggregation.'},
 {'metadata_field': 'time_period',
  'observed_value': '2013',
  'description': 'The year or period covered by the data in the figure.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'The figure title includes 2013, which is essential for temporal search, comparison, and analytical reuse.'},
 {'metadata_field': 'unit_of_measure',
  'observed_value': 'نسبة مئوية',
  'description': 'The measurement unit used for the displayed values.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'The unit indicates that the values are percentages, which is necessary for interpreting and reusing the data correctly.'},
 {'metadata_field': 'category_dimension',
  'observed_value': 'Loan source type',
  'description': 'The categorical dimension used to divide the data values in the figure.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'The pie chart categories represent different sources of loans, a reusable dimension useful for discovery of figures organized by financing source or provider type.'},
 {'metadata_field': 'category_labels',
  'observed_value': 'مؤسسة مالية رسمية؛ الأسرة أو الأصدقاء؛ جهة إقراض خاصة غير رسمية',
  'description': 'The category names or legend labels used in the figure.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'Category labels expose substantive information not necessarily captured in document-level metadata, enabling searches for formal financial institutions, family or friends, and informal private lenders.'},
 {'metadata_field': 'category_values',
  'observed_value': '77؛ 6؛ 17',
  'description': 'The numeric values associated with the figure categories.',
  'source_level': 'snapshot',
  'discovery_value': 'medium',
  'reasoning': 'Capturing category values supports analytical reuse and allows users to discover figures containing quantitative distributions, although the labels are needed for full interpretation.'},
 {'metadata_field': 'category_value_pairs',
  'observed_value': 'مؤسسة مالية رسمية: 77؛ الأسرة أو الأصدقاء: 6؛ جهة إقراض خاصة غير رسمية: 17',
  'description': 'The pairing of category labels with their corresponding numeric values.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'Pairing labels and values makes the chart data directly reusable and searchable, preserving the semantic meaning of each percentage.'},
 {'metadata_field': 'source_citation',
  'observed_value': 'المصدر: دراسة استقصائية لمناخ الاستثمار (2012).',
  'description': 'The cited data source or provenance statement shown with the figure.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'The source citation supports provenance tracking and helps users assess the origin and credibility of the figure data.'},
 {'metadata_field': 'data_source_name',
  'observed_value': 'دراسة استقصائية لمناخ الاستثمار',
  'description': 'The named survey, dataset, report, or source from which the figure data were derived.',
  'source_level': 'snapshot',
  'discovery_value': 'high',
  'reasoning': 'A structured data source name enables discovery of figures based on common source datasets or surveys, such as investment climate surveys.'},
 {'metadata_field': 'data_source_year',
  'observed_value': '2012',
  'description': 'The year associated with the cited data source, if distinct from the figure data period.',
  'source_level': 'snapshot',
  'discovery_value': 'medium',
  'reasoning': 'The source citation includes 2012, which may be useful for provenance and version tracking, especially because it differs from the 2013 year in the figure title.'},
 {'metadata_field': 'language',
  'observed_value': 'Arabic',
  'description': 'The language used in the figure or source document.',
  'source_level': 'both',
  'discovery_value': 'medium',
  'reasoning': 'The snapshot text is in Arabic and the document metadata lists Arabic; language metadata supports multilingual search, translation workflows, and language-based filtering.'},
 {'metadata_field': 'document_title',
  'observed_value': 'Jordan - Enhancing Governance and Strengthening the Regulatory and Institutional Framework for Micro, Small, and Medium Enterprise (MSME) Development Project',
  'description': 'The title of the source document containing the figure.',
  'source_level': 'document',
  'discovery_value': 'medium',
  'reasoning': 'Linking the figure to the source document title supports provenance, contextual discovery, and retrieval of the complete document.'},
 {'metadata_field': 'document_type',
  'observed_value': 'Project Appraisal Document',
  'description': 'The type or genre of the source document.',
  'source_level': 'document',
  'discovery_value': 'medium',
  'reasoning': 'Document type supports filtering figures by publication context, such as project appraisal documents versus analytical reports.'},
 {'metadata_field': 'project_id',
  'observed_value': 'P147875',
  'description': 'The project identifier associated with the source document.',
  'source_level': 'document',
  'discovery_value': 'high',
  'reasoning': 'Project identifiers allow figures to be linked to World Bank projects and support retrieval across related project documents.'},
 {'metadata_field': 'sector',
  'observed_value': 'Financial Sector',
  'description': 'The sector classification assigned to the source document or project.',
  'source_level': 'document',
  'discovery_value': 'medium',
  'reasoning': 'Sector metadata supports domain-level filtering and helps connect the loan-source figure to broader financial sector content.'}]